### ISSUE TITLE
update

### ISSUE THREAD

**Issue by DimonYoing** [ErosionYT/Erosions-Essentials#3]
Please add a lot of commands like in Essentials PE

**Comment by ErosionYT** [comment]
What would you like added?

**Comment by DimonYoing** [comment]
command /speed [1-10] [player]
/jail [player] [time] [reason]
/unjail [player]
/setjail
/deljail
But only for the commands to work WITHOUT specifying a FULL nmkname

**Comment by DimonYoing** [comment]
To make it clear to everyone that the player will be sent to jail

**Comment by DimonYoing** [comment]
So that the admin prefix from pureperms is also supported

**Comment by ErosionYT** [comment]
> command /speed [1-10] [player] /jail [player] [time] [reason] /unjail [player] /setjail /deljail But only for the commands to work WITHOUT specifying a FULL nmkname

With the `Jail` command, is that like a freeze command or ban?

**Comment by DimonYoing** [comment]
команда тюрьмы
